export const emoteList: RegExp[] = [
  /^You agree\.$/u,
  /^You agree with [\p{L}]*\.$/u,
  /^[\p{L}]* agrees\.$/u,
  /^[\p{L}]* agrees with [\p{L}]*\.$/u,
  /^You are amazed!$/u,
  /^You are amazed by [\p{L}]*\.$/u,
  /^[\p{L}]* is amazed!$/u,
  /^[\p{L}]* is amazed by [\p{L}]*\.$/u,
  /^You raise your fist in anger\.$/u,
  /^You raise your fist in anger at [\p{L}]*\.$/u,
  /^[\p{L}]* raises (\bhis|\bher|\bhim) fist in anger\.$/u,
  /^[\p{L}]* raises (\bhis|\bher|\bhim) fist in anger at [\p{L}]*\.$/u,
  /^You apologize to everyone\. Sorry!$/u,
  /^You apologize to [\p{L}]*\. Sorry!$/u,
  /^[\p{L}]* apologizes to everyone\. Sorry!$/u,
  /^[\p{L}]* apologizes to [\p{L}]*\. Sorry!$/u,
  /^You applaud\. Bravo!$/u,
  /^You applaud at [\p{L}]*\. Bravo!$/u,
  /^[\p{L}]* applauds\. Bravo!$/u,
  /^[\p{L}]* applauds at [\p{L}]*\. Bravo!$/u,
  /^You tell everyone to attack something\.$/u,
  /^You tell everyone to attack [\p{L}]*\.$/u,
  /^[\p{L}]* tells everyone to attack something\.$/u,
  /^[\p{L}]* tells everyone to attack [\p{L}]*\.$/u,
  /^You bark\. Woof woof!$/u,
  /^You bark at [\p{L}]*\.$/u,
  /^[\p{L}]* barks\. Woof woof!$/u,
  /^[\p{L}]* barks at [\p{L}]*\.$/u,
  /^You are bashful\.$/u,
  /^You are so bashful\.\.\.too bashful to get [\p{L}]*'s attention\.$/u,
  /^[\p{L}]* is bashful\.$/u,
  /^[\p{L}]* is so bashful\.\.\.too bashful to get [\p{L}]*'s attention\.$/u,
  /^You beckon everyone over to you\. $/u,
  /^You beckon [\p{L}]* over\.$/u,
  /^[\p{L}]* beckons everyone over to\. $/u,
  /^[\p{L}]* beckons [\p{L}]* over\.$/u,
  /^You beg everyone around you\. How pathetic\.$/u,
  /^You beg [\p{L}]*\. How pathetic\.$/u,
  /^[\p{L}]* begs everyone around (\bhis|\bher|\bhim)\. How pathetic\.$/u,
  /^[\p{L}]* begs [\p{L}]*\. How pathetic\.$/u,
  /^You let out a loud belch\.$/u,
  /^You burp rudely in [\p{L}]*'s face\.$/u,
  /^[\p{L}]* lets out a loud belch\.$/u,
  /^[\p{L}]* burps rudely in [\p{L}]*'s face\.$/u,
  /^You look around for someone to bite\.$/u,
  /^You bite [\p{L}]*\. Ouch!$/u,
  /^[\p{L}]* looks around for someone to bite\.$/u,
  /^[\p{L}]* bites [\p{L}]*\. Ouch!$/u,
  /^You look around\.$/u,
  /^You looks at [\p{L}]*\.$/u,
  /^[\p{L}]* looks around\.$/u,
  /^[\p{L}]* looks at [\p{L}]*\.$/u,
  /^You blink your eyes\. $/u,
  /^You blink at [\p{L}]*\.$/u,
  /^[\p{L}]* blinks\. $/u,
  /^[\p{L}]* blinks at [\p{L}]*\.$/u,
  /^You blush\.$/u,
  /^You blush at [\p{L}]*\.$/u,
  /^[\p{L}]* blushes\.$/u,
  /^[\p{L}]* blushes at [\p{L}]*\.$/u,
  /^You boggle at the situation\.$/u,
  /^You boggle at [\p{L}]*\.$/u,
  /^[\p{L}]* boggles at the situation\.$/u,
  /^[\p{L}]* boggles at [\p{L}]*\.$/u,
  /^You bonk yourself on the noggin\. Doh!$/u,
  /^You bonk [\p{L}]* on the noggin\. Doh!$/u,
  /^[\p{L}]* bonks (\bhis|\bher|\bhim) own noggin\. Doh!$/u,
  /^[\p{L}]* bonks [\p{L}]* on the noggin\. Doh!$/u,
  /^You are overcome with boredom\. Oh the drudgery!$/u,
  /^You are terribly bored with [\p{L}]*\.$/u,
  /^[\p{L}]* is overcome with boredom\. Oh the drudgery!$/u,
  /^[\p{L}]* is terribly bored with [\p{L}]*\.$/u,
  /^You bounce up and down\.$/u,
  /^You bounce up and down in front of [\p{L}]*\.$/u,
  /^[\p{L}]* bounces up and down\.$/u,
  /^[\p{L}]* bounces up and down in front of [\p{L}]*\.$/u,
  /^You bow down graciously\.$/u,
  /^You bow before [\p{L}]*\.$/u,
  /^[\p{L}]* bows down graciously\.$/u,
  /^[\p{L}]* bows before [\p{L}]*\.$/u,
  /^You brandish your weapon fiercely\.$/u,
  /^You brandish your weapon fiercely at [\p{L}]*\.$/u,
  /^[\p{L}]* brandishes (\bhis|\bher|\bhim) weapon fiercely\.$/u,
  /^[\p{L}]* brandishes (\bhis|\bher|\bhim) weapon fiercely at [\p{L}]*\.$/u,
  /^You let everyone know you'll be right back$/u,
  /^You let [\p{L}]* know you'll be right back\.$/u,
  /^[\p{L}]* will be right back\.$/u,
  /^[\p{L}]* will be right back\. Sit tight, [\p{L}]*\.$/u,
  /^You cackle maniacally at the situation\.$/u,
  /^You cackle maniacally at [\p{L}]*\.$/u,
  /^[\p{L}]* cackles maniacally at the situation\.$/u,
  /^[\p{L}]* cackles maniacally at [\p{L}]*\.$/u,
  /^You remain calm\.$/u,
  /^You try to calm [\p{L}]* down\.$/u,
  /^[\p{L}]* remains calm\.$/u,
  /^[\p{L}]* tries to calm [\p{L}]* down\.$/u,
  /^You scratch yourself\. Ah, much better!$/u,
  /^You scratch [\p{L}]*\. How catty!$/u,
  /^[\p{L}]* scratches (\bhis|\bher|\bhim)self\. Ah, much better!$/u,
  /^[\p{L}]* scratches [\p{L}]*\. How catty!$/u,
  /^You start to charge\.$/u,
  /^[\p{L}]* starts to charge\.$/u,
  /^You cheer!$/u,
  /^You cheer at [\p{L}]*\.$/u,
  /^[\p{L}]* cheers!$/u,
  /^[\p{L}]* cheers at [\p{L}]*\.$/u,
  /^You begin to eat\.$/u,
  /^You begin to eat in front of [\p{L}]*\.$/u,
  /^[\p{L}]* begins to eat\.$/u,
  /^[\p{L}]* begins to eat in front of [\p{L}]*\.$/u,
  /^With arms flapping, you strut around\. Cluck, Cluck, Chicken!$/u,
  /^With arms flapping, you strut around [\p{L}]*\. Cluck, Cluck, Chicken!$/u,
  /^With arms flapping, [\p{L}]* struts around\. Cluck, Cluck, Chicken!$/u,
  /^With arms flapping, [\p{L}]* struts around [\p{L}]*\. Cluck, Cluck, Chicken!$/u,
  /^You let out a hearty chuckle\. $/u,
  /^You chuckle at [\p{L}]*\.$/u,
  /^[\p{L}]* lets out a hearty chuckle\. $/u,
  /^[\p{L}]* chuckles at [\p{L}]*\.$/u,
  /^You clap excitedly\.$/u,
  /^You clap excitedly for [\p{L}]*\.$/u,
  /^[\p{L}]* claps excitedly\.$/u,
  /^[\p{L}]* claps excitedly for [\p{L}]*\.$/u,
  /^You let everyone know that you are cold\.$/u,
  /^You let [\p{L}]* know that you are cold\.$/u,
  /^[\p{L}]* lets everyone know that (\bhis|\bher|\bhim) is cold\.$/u,
  /^[\p{L}]* lets [\p{L}]* know that (\bhis|\bher|\bhim) is cold\.$/u,
  /^You need to be comforted\. $/u,
  /^You comfort [\p{L}]*\.$/u,
  /^[\p{L}]* needs to be comforted\. $/u,
  /^[\p{L}]* comforts [\p{L}]*\.$/u,
  /^You commend everyone on a job well done\.$/u,
  /^You commend [\p{L}]* on a job well done\.$/u,
  /^You are hopelessly confused\.$/u,
  /^You look at [\p{L}]* with a confused look\.$/u,
  /^[\p{L}]* is hopelessly confused\.$/u,
  /^[\p{L}]* looks at [\p{L}]* with a confused look\.$/u,
  /^You congratulate everyone around you\.$/u,
  /^You congratulate [\p{L}]*\.$/u,
  /^[\p{L}]* congratulate everyone\.$/u,
  /^[\p{L}]* congratulates [\p{L}]*\.$/u,
  /^You let out a hacking cough\. $/u,
  /^You cough at [\p{L}]*\.$/u,
  /^[\p{L}]* lets out a hacking cough\. $/u,
  /^[\p{L}]* coughs at [\p{L}]*\.$/u,
  /^You cower in fear\.$/u,
  /^You cower in fear at the sight of [\p{L}]*\.$/u,
  /^[\p{L}]* cowers in fear\.$/u,
  /^[\p{L}]* cowers in fear at the sight of [\p{L}]*\.$/u,
  /^You crack your knuckles\.$/u,
  /^You crack your knuckles while staring at [\p{L}]*\.$/u,
  /^[\p{L}]* cracks (\bhis|\bher|\bhim) knuckles\.$/u,
  /^[\p{L}]* cracks (\bhis|\bher|\bhim) knuckles while staring at [\p{L}]*\.$/u,
  /^You cringe in fear\.$/u,
  /^You cringe away from [\p{L}]*\.$/u,
  /^[\p{L}]* cringes in fear\.$/u,
  /^[\p{L}]* cringes away from [\p{L}]*\.$/u,
  /^You need to be cuddled\.$/u,
  /^You cuddle up against [\p{L}]*\.$/u,
  /^[\p{L}]* needs to be cuddled\.$/u,
  /^[\p{L}]* cuddles up against [\p{L}]*\.$/u,
  /^You express your curiosity to those around you\.$/u,
  /^You are curious what [\p{L}]* is up to\.$/u,
  /^[\p{L}]* expresses (\bhis|\bher|\bhim) curiosity to those around you\.$/u,
  /^[\p{L}]* is curious what [\p{L}]* is up to\.$/u,
  /^You curtsey\.$/u,
  /^You curtsey before [\p{L}]*\.$/u,
  /^[\p{L}]* curtsies\.$/u,
  /^[\p{L}]* curtsey before [\p{L}]*\.$/u,
  /^You burst into dance\. $/u,
  /^You dance with [\p{L}]*\.$/u,
  /^[\p{L}]* bursts into dance\. $/u,
  /^[\p{L}]* dances with [\p{L}]*\.$/u,
  /^You reached a new level\. DING!$/u,
  /^You congratulate [\p{L}]* on a new level\. DING!$/u,
  /^You frown\.$/u,
  /^You frown with disappointment at [\p{L}]*\.$/u,
  /^[\p{L}]* frowns\.$/u,
  /^[\p{L}]* frowns with disappointment at [\p{L}]*\.$/u,
  /^You threaten everyone with the wrath of doom\.$/u,
  /^You threaten [\p{L}]* with the wrath of doom\.$/u,
  /^[\p{L}]* threatens everyone with the wrath of doom\.$/u,
  /^[\p{L}]* threatens [\p{L}]* with the wrath of doom\.$/u,
  /^You raise a drink in the air before chugging it down\. Cheers!$/u,
  /^You raise a drink to [\p{L}]*\. Cheers!$/u,
  /^[\p{L}]* raises a drink in the air before chugging it down\. Cheers!$/u,
  /^[\p{L}]* raises a drink to [\p{L}]*\. Cheers!$/u,
  /A tendril of drool runs down your lip\.$/u,
  /^You look at [\p{L}]* and begin to drool\.$/u,
  /^You duck for cover\.$/u,
  /^You duck behind [\p{L}]*\.$/u,
  /^You talk excitedly with everyone\.$/u,
  /^You talk excitedly with [\p{L}]*\.$/u,
  /^You cross your eyes\.$/u,
  /^You eye [\p{L}]* up and down\.$/u,
  /^You cover your face with your palm\.$/u,
  /^You look over at [\p{L}]* and cover your face with your palm\.$/u,
  /^[\p{L}]* covers (\bhis|\bher|\bhim) face with your palm\.$/u,
  /^[\p{L}]* looks over at [\p{L}]* and covers (\bhis|\bher|\bhim) face with your palm\.$/u,
  /^You wave goodbye to everyone\. Farewell!$/u,
  /^You wave goodbye to [\p{L}]*\. Farewell!$/u,
  /^[\p{L}]* waves goodbye to everyone\. Farewell!$/u,
  /^[\p{L}]* waves goodbye to [\p{L}]*\. Farewell!$/u,
  /^You fart loudly\. Whew\.\.\.what stinks?$/u,
  /^You brush up against [\p{L}]* and fart loudly\.$/u,
  /^[\p{L}]* farts loudly\. Whew\.\.\.what stinks?$/u,
  /^[\p{L}]* brushes up against [\p{L}]* and farts loudly\.$/u,
  /^You fidget\.$/u,
  /^You fidget impatiently while waiting for [\p{L}]*\.$/u,
  /^You yell for everyone to flee!$/u,
  /^You yell for [\p{L}]* to flee!$/u,
  /^You flex your muscles\. Oooooh so strong!$/u,
  /^You flex at [\p{L}]*\. Oooooh so strong!$/u,
  /^You flirt\. $/u,
  /^You flirt with [\p{L}]*\.$/u,
  /^You flop about helplessly\.$/u,
  /^You flop about helplessly around [\p{L}]*\.$/u,
  /^You motion for everyone to follow\.$/u,
  /^You motion for [\p{L}]* to follow\.$/u,
  /^You are hungry!$/u,
  /^You are hungry\. Maybe [\p{L}]* has some food\.\.\.$/u,
  /^You gasp\.$/u,
  /^You gasp at [\p{L}]*\.$/u,
  /^[\p{L}]* gasps\.$/u,
  /^[\p{L}]* gasps at [\p{L}]*\.$/u,
  /^You gaze off into the distance\.$/u,
  /^You gaze longingly at [\p{L}]*\.$/u,
  /^You giggle\.$/u,
  /^You giggle at [\p{L}]*\.$/u,
  /^You are filled with happiness!$/u,
  /^You are very happy with [\p{L}]*!$/u,
  /^You glare angrily\.$/u,
  /^You glare angrily at [\p{L}]*\.$/u,
  /^[\p{L}]* glares angrily\.$/u,
  /^[\p{L}]* glares angrily at [\p{L}]*\.$/u,
  /^You gloat over everyone's misfortune\.$/u,
  /^You gloat over [\p{L}]*'s misfortune\.$/u,
  /^You clap half heartedly, clearly unimpressed\.$/u,
  /^You clap for [\p{L}]*, clearly unimpressed\.$/u,
  /^You greet everyone warmly\.$/u,
  /^You greet [\p{L}]* warmly\.$/u,
  /^[\p{L}]* greets everyone warmly\.$/u,
  /^[\p{L}]* greets [\p{L}]* warmly\.$/u,
  /^You grin wickedly\.$/u,
  /^You grin wickedly at [\p{L}]*\.$/u,
  /^[\p{L}]* grins wickedly\.$/u,
  /^[\p{L}]* grins wickedly at [\p{L}]*\.$/u,
  /^You begin to groan\.$/u,
  /^You look at [\p{L}]* and groan\.$/u,
  /^[\p{L}]* begins to groan\.$/u,
  /^[\p{L}]* looks at [\p{L}]* and groans\.$/u,
  /^You grovel on the ground, wallowing in subservience\.$/u,
  /^You grovel before [\p{L}]* like a subservient peon\.$/u,
  /^You growl menacingly\.$/u,
  /^You growl menacingly at [\p{L}]*\.$/u,
  /^[\p{L}]* growls menacingly\.$/u,
  /^[\p{L}]* growls menacingly at [\p{L}]*\.$/u,
  /^You let out a boisterous guffaw!$/u,
  /^You take one look at [\p{L}]* and let out a guffaw!$/u,
  /^You hail those around you\.$/u,
  /^You hail [\p{L}]*\.$/u,
  /^You call out for healing!$/u,
  /^You greet everyone with a hearty hello!$/u,
  /^You greet [\p{L}]* with a hearty hello!$/u,
  /^[\p{L}]* greets everyone with a hearty hello!$/u,
  /^[\p{L}]* greets [\p{L}]* with a hearty hello!$/u,
  /^You cry out for help!$/u,
  /^You put up your hand for a high five\.$/u,
  /^You give [\p{L}]* a high five!$/u,
  /^You need a hug!$/u,
  /^You hug [\p{L}]*\.$/u,
  /^You warn everyone of incoming enemies!$/u,
  /^You point out [\p{L}]* as an incoming enemy!$/u,
  /^You think everyone around you is a son of a motherless ogre\.$/u,
  /^You think [\p{L}]* is the son of a motherless ogre\.$/u,
  /^You introduce yourself to everyone\.$/u,
  /^You introduce yourself to [\p{L}]*\.$/u,
  /^You were just kidding!$/u,
  /^You let [\p{L}]* know that you were just kidding!$/u,
  /^You blow a kiss into the wind\.$/u,
  /^You blow a kiss to [\p{L}]*\.$/u,
  /^You kneel down\.$/u,
  /^You kneel before [\p{L}]*\.$/u,
  /^[\p{L}]* kneels down\.$/u,
  /^[\p{L}]* kneels before [\p{L}]*\.$/u,
  /^You laugh\. $/u,
  /^You laugh at [\p{L}]*\.$/u,
  /^[\p{L}]* laughs\. $/u,
  /^[\p{L}]* laughs at [\p{L}]*\.$/u,
  /^You praise the Light\.$/u,
  /^You lavish praise upon [\p{L}]*\.$/u,
  /^You lie down\.$/u,
  /^You lie down before [\p{L}]*\.$/u,
  /^[\p{L}]* lies down\.$/u,
  /^[\p{L}]* lies down before [\p{L}]*\.$/u,
  /^You lick your lips\.$/u,
  /^You lick [\p{L}]*\.$/u,
  /^[\p{L}]* licks your lips\.$/u,
  /^[\p{L}]* licks [\p{L}]*\.$/u,
  /^You are listening!$/u,
  /^You listen intently to [\p{L}]*\.$/u,
  /^You are hopelessly lost\.$/u,
  /^You want [\p{L}]* to know that you are hopelessly lost\.$/u,
  /^You feel the love\. $/u,
  /^You love [\p{L}]*\.$/u,
  /^You need a massage!$/u,
  /^You massage [\p{L}]*'s shoulders\.$/u,
  /^You moan suggestively\.$/u,
  /^You moan suggestively at [\p{L}]*\.$/u,
  /^[\p{L}]* moans suggestively\.$/u,
  /^[\p{L}]* moans suggestively at [\p{L}]*\.$/u,
  /^You mock life and all it stands for\.$/u,
  /^You mock the foolishness of [\p{L}]*\.$/u,
  /^You moo at [\p{L}]*\. Mooooooooooo\.$/u,
  /^[\p{L}]* moos at [\p{L}]*\. Mooooooooooo\.$/u,
  /^You drop your trousers and moon everyone\.$/u,
  /^You drop your trousers and moon [\p{L}]*\.$/u,
  /In quiet contemplation, you mourn the loss of the dead\.$/u,
  /In quiet contemplation, you mourn the death of [\p{L}]*\.$/u,
  /^You clearly state, NO\.$/u,
  /^You tell [\p{L}]* NO\. Not going to happen\.$/u,
  /^[\p{L}]* clearly states, NO\.$/u,
  /^[\p{L}]* tells [\p{L}]* NO\. Not going to happen\.$/u,
  /^You nod\.$/u,
  /^You nod at [\p{L}]*\.$/u,
  /^[\p{L}]* nods\.$/u,
  /^[\p{L}]* nods at [\p{L}]*\.$/u,
  /^With a finger deep in one nostril, you pass the time\.$/u,
  /^You pick your nose and show it to [\p{L}]*\.$/u,
  /^You announce that you have low mana!$/u,
  /^You give the order to open fire\.$/u,
  /^You run around in a frenzied state of panic\.$/u,
  /^You take one look at [\p{L}]* and panic\.$/u,
  /^You need a pat\. $/u,
  /^You gently pat [\p{L}]*\.$/u,
  /^You peer around, searchingly\.$/u,
  /^You peer at [\p{L}]* searchingly\.$/u,
  /^[\p{L}]* peers around, searchingly\.$/u,
  /^[\p{L}]* peers at [\p{L}]* searchingly\.$/u,
  /^You shoo the measly pests away\.$/u,
  /^You shoo [\p{L}]* away\. Be gone pest!$/u,
  /^[\p{L}]* shoos the measly pests away\.$/u,
  /^[\p{L}]* shoos [\p{L}]* away\. Be gone pest!$/u,
  /^You pity those around you\.$/u,
  /^You look down upon [\p{L}]* with pity\.$/u,
  /^You drop to your knees and plead in desperation\.$/u,
  /^You plead with [\p{L}]*\.$/u,
  /^You point over yonder\.$/u,
  /^You point at [\p{L}]*\.$/u,
  /^[\p{L}]* points over yonder\.$/u,
  /^[\p{L}]* points at [\p{L}]*\.$/u,
  /^You poke your belly and giggle\.$/u,
  /^You poke [\p{L}]*\. Hey!$/u,
  /^You ponder the situation\.$/u,
  /^You ponder [\p{L}]*'s actions\.$/u,
  /^You pounce out from the shadows\.$/u,
  /^You pounce on top of [\p{L}]*\.$/u,
  /^[\p{L}]* pounces out from the shadows\.$/u,
  /^[\p{L}]* pounces on top of [\p{L}]*\.$/u,
  /^You pray to the Gods\.$/u,
  /^You say a prayer for [\p{L}]*\.$/u,
  /^You purr like a kitten\.$/u,
  /^You purr at [\p{L}]*\.$/u,
  /^[\p{L}]* purrs like a kitten\.$/u,
  /^[\p{L}]* purrs at [\p{L}]*\.$/u,
  /^You are puzzled\. What's going on here?$/u,
  /^You are puzzled by [\p{L}]*\.$/u,
  /^You want to know the meaning of life\.$/u,
  /^You question [\p{L}]*\.$/u,
  /^You raise your hand in the air\.$/u,
  /^You look at [\p{L}]* and raise your hand\.$/u,
  /^You make a rude gesture\.$/u,
  /^You make a rude gesture at [\p{L}]*\.$/u,
  /^You let everyone know that you are ready!$/u,
  /^You let [\p{L}]* know that you are ready!$/u,
  /^You shake your rear\.$/u,
  /^You shake your rear at [\p{L}]*\.$/u,
  /^You are filled with regret\.$/u,
  /^You think that [\p{L}]* will regret it\.$/u,
  /^You roar with bestial vigor\. So fierce!$/u,
  /^You roar with bestial vigor at [\p{L}]*\. So fierce!$/u,
  /^[\p{L}]* roars with bestial vigor\. So fierce!$/u,
  /^[\p{L}]* roars with bestial vigor at [\p{L}]*\. So fierce!$/u,
  /^You roll on the floor laughing\.$/u,
  /^You roll on the floor laughing at [\p{L}]*\.$/u,
  /^You roll you eyes\.$/u,
  /^You roll your eyes at [\p{L}]*\.$/u,
  /^[\p{L}]* rolls (\bhis|\bher|\bhim) eyes\.$/u,
  /^[\p{L}]* rolls (\bhis|\bher|\bhim) eyes at [\p{L}]*\.$/u,
  /^You hang your head dejectedly\.$/u,
  /^[\p{L}]* hangs (\bhis|\bher|\bhim) head dejectedly\.$/u,
  /^You stand at attention and salute\.$/u,
  /^You salute [\p{L}]* with respect\.$/u,
  /^[\p{L}]* stands at attention and salutes\.$/u,
  /^[\p{L}]* salutes [\p{L}]* with respect\.$/u,
  /^You are scared!$/u,
  /^You are scared of [\p{L}]*\.$/u,
  /^[\p{L}]* is scared!$/u,
  /^[\p{L}]* is scared of [\p{L}]*\.$/u,
  /^You're too sexy for your tunic\.\.\.so sexy it hurts\.$/u,
  /^You think [\p{L}]* is a sexy devil\.$/u,
  /^You shimmy before the masses\.$/u,
  /^You shimmy before [\p{L}]*\.$/u,
  /^You shiver in your boots\. Chilling!$/u,
  /^You shiver beside [\p{L}]*\. Chilling!$/u,
  /^You shrug\. Who knows?$/u,
  /^You shrug at [\p{L}]*\. Who knows?$/u,
  /^[\p{L}]* shrugs\. Who knows?$/u,
  /^[\p{L}]* shrugs at [\p{L}]*\. Who knows?$/u,
  /^You smile shyly\.$/u,
  /^You smile shyly at [\p{L}]*\.$/u,
  /^[\p{L}]* smiles shyly\.$/u,
  /^[\p{L}]* smiles shyly at [\p{L}]*\.$/u,
  /^You let out a long, drawn-out sigh\.$/u,
  /^You sigh at [\p{L}]*\.$/u,
  /^[\p{L}]* lets out a long, drawn-out sigh\.$/u,
  /^[\p{L}]* sighs at [\p{L}]*\.$/u,
  /^You tell a joke\.$/u,
  /^You tell [\p{L}]* a joke\.$/u,
  /^You slap yourself across the face\. Ouch!$/u,
  /^You slap [\p{L}]* across the face\. Ouch!$/u,
  /^You fall asleep\. Zzzzzzz\. $/u,
  /^[\p{L}]* falls asleep\. Zzzzzzz\.$/u,
  /^You smell the air around you\. Wow, someone stinks!$/u,
  /^You smell [\p{L}]*\. Wow, someone stinks!$/u,
  /^You smile\.$/u,
  /^You smile at [\p{L}]*\.$/u,
  /^[\p{L}]* smiles\.$/u,
  /^[\p{L}]* smiles at [\p{L}]*\.$/u,
  /^A sly smirk spreads across your face\.$/u,
  /^You smirk slyly at [\p{L}]*\.$/u,
  /^A sly smirk spreads across [\p{L}]*'s face\.$/u,
  /^[\p{L}]* smirks slyly at [\p{L}]*\.$/u,
  /^You bare your teeth and snarl\.$/u,
  /^You bare your teeth and snarl at [\p{L}]*\.$/u,
  /^[\p{L}]* bares (\bhis|\bher|\bhim) teeth and snarls\.$/u,
  /^[\p{L}]* bares (\bhis|\bher|\bhim) teeth and snarls at [\p{L}]*\.$/u,
  /^You sneeze\. Achoo!$/u,
  /^You sneeze on [\p{L}]*;$/u,
  /^You quietly snicker to yourself\.$/u,
  /^You snicker at [\p{L}]*\.$/u,
  /^[\p{L}]* quietly snickers to (\bhis|\bher|\bhim)self\.$/u,
  /^[\p{L}]* snickers at [\p{L}]*\.$/u,
  /^You sniff the air around you\.$/u,
  /^You sniff [\p{L}]*\.$/u,
  /^[\p{L}]* sniffs the air around (\bhis|\bher|\bhim)\.$/u,
  /^[\p{L}]* sniffs [\p{L}]*\.$/u,
  /^You snub all of the lowly peons around you\.$/u,
  /^You snub [\p{L}]*\.$/u,
  /^You cry\.$/u,
  /^You cry on [\p{L}]*'s shoulder\.$/u,
  /^[\p{L}]* cries\.$/u,
  /^[\p{L}]* cries on [\p{L}]*'s shoulder\.$/u,
  /^You need to be soothed\.$/u,
  /^You soothe [\p{L}]*\. There, there\.\.\.things will be ok\.$/u,
  /^You spit on the ground\.$/u,
  /^You spit on [\p{L}]*\.$/u,
  /^[\p{L}]* spits on the ground\.$/u,
  /^[\p{L}]* spits on [\p{L}]*\.$/u,
  /^You stare off into the distance\.$/u,
  /^You stare [\p{L}]* down\.$/u,
  /^[\p{L}]* stares off into the distance\.$/u,
  /^[\p{L}]* stares [\p{L}]* down\.$/u,
  /^You flex your muscles\. Oooooh so strong!$/u,
  /^You flex at [\p{L}]*\. Oooooh so strong!$/u,
  /^You are so surprised!$/u,
  /^You are surprised by [\p{L}]*'s actions\.$/u,
  /^You surrender to your opponents\.$/u,
  /^You surrender before [\p{L}]*\. Such is the agony of defeat\.\.\.$/u,
  /^You talk to yourself since no one else seems interested$/u,
  /^You want to talk things over with [\p{L}]*$/u,
  /^You talk excitedly with everyone$/u,
  /^You talk excitedly with [\p{L}]*$/u,
  /^You tap your foot\. Hurry up already!$/u,
  /^You tap your foot as you wait for [\p{L}]*\.$/u,
  /^You taunt everyone around you\. Bring it fools!$/u,
  /^You make a taunting gesture at [\p{L}]*\. Bring it!$/u,
  /^You are such a tease\.$/u,
  /^You tease [\p{L}]*\.$/u,
  /^You are lost in thought\. $/u,
  /^You think about [\p{L}]*\.$/u,
  /^You are so thirsty\. Can anyone spare a drink?$/u,
  /^You let [\p{L}]* know you are thirsty\. Spare a drink?$/u,
  /^You want to be tickled\. Hee hee!$/u,
  /^You tickle [\p{L}]*\. Hee hee!$/u,
  /^[\p{L}]* wants to be tickled\. Hee hee!$/u,
  /^[\p{L}]* tickles [\p{L}]*\. Hee hee!$/u,
  /^You let everyone know that you are tired\.$/u,
  /^You let [\p{L}]* know that you are tired\.$/u,
  /^You thank everyone around you\.$/u,
  /^You thank [\p{L}]*\.$/u,
  /^[\p{L}]* thanks everyone around you\.$/u,
  /^[\p{L}]* thanks [\p{L}]*\.$/u,
  /^You veto the motion on the floor\.$/u,
  /^You veto [\p{L}]*'s motion\.$/u,
  /^You bask in the glory of victory\.$/u,
  /^You bask in the glory of victory with [\p{L}]*\.$/u,
  /^You begin to play the world's smallest violin\.$/u,
  /^You play the world's smallest violin for [\p{L}]*\.$/u,
  /^You ask everyone to wait\.$/u,
  /^You ask [\p{L}]* to wait\.$/u,
  /^[\p{L}]* asks [\p{L}]* to wait\.$/u,
  /^[\p{L}]* asks [\p{L}]* to wait\.$/u,
  /^You wave\.$/u,
  /^You wave at [\p{L}]*\.$/u,
  /^[\p{L}]* waves\.$/u,
  /^[\p{L}]* waves at [\p{L}]*\.$/u,
  /^You welcome everyone\.$/u,
  /^You welcome [\p{L}]*\.$/u,
  /^[\p{L}]* welcomes everyone\.$/u,
  /^[\p{L}]* welcomes [\p{L}]*\.$/u,
  /^You whine pathetically\.$/u,
  /^You whine pathetically at [\p{L}]*\.$/u,
  /^You let forth a sharp whistle\.$/u,
  /^You whistle at [\p{L}]*\.$/u,
  /^You are blown away\. $/u,
  /^You are blown away by [\p{L}]*\.$/u,
  /^You wink slyly\.$/u,
  /^You wink slyly at [\p{L}]*\.$/u,
  /^[\p{L}]* winks slyly\.$/u,
  /^[\p{L}]* winks slyly at [\p{L}]*\.$/u,
  /^You begin to work\.$/u,
  /^You work with [\p{L}]*\.$/u,
  /^You yawn sleepily\.$/u,
  /^You yawn sleepily at [\p{L}]*\.$/u,
  /^[\p{L}]* yawns sleepily\.,$/u,
  /^[\p{L}]* yawns sleepily at [\p{L}]*\.$/u,
  /^You were happy to help\.$/u,
  /^You were happy to help [\p{L}]*\.$/u,
];
